FROM node:16

WORKDIR /app

RUN npm install -g @usebruno/cli@1.35
COPY ./test /app
ENV CI=true
RUN npm install
ENV POST_MSG_HEAD=""
ENV DISCORD_WEBHOOK_URL=""

CMD ["/bin/bash", "-c", "./run_tests.sh ${DISCORD_WEBHOOK_URL} ${POST_MSG_HEAD}"]